name: Gradle Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
            java-version: '19'
            distribution: 'adopt'
      - name: Build with Gradle
        run: |
            chmod +x gradlew
            shell: bash
            - name: Build and test with Gradle
              run: ./gradlew clean test
    
